vision_language_model:
    ros__parameters:
        vlm_api_type: openai #Must be one of: ['openai', 'ollama', 'google-genai']
        vlm_api_host: https://api.openai.com/v1 #Must be set for openai and ollama, but is not used for google-genai
        vlm_api_model: gpt-4o

        subscribers:
            image_rgb:
                topic: /cam1/color/image_raw

        servers:
            visual_question_answering:
                service: /fbot_vision/bvlm/visual_question_answering/query
