vision_language_model:
    ros__parameters:
        vlm_api_type: openai #Must be one of: ['openai', 'ollama', 'google-genai']
        vlm_api_host: dummy #Must be set for openai and ollama, but is not used for google-genai
        vlm_api_model: gemini-1.5-flash

        subscribers:
            image_rgb:
                topic: /camera/camera/color/image_raw

        servers:
            visual_question_answering:
                service: /fbot_vision/bvlm/visual_question_answering/query
