yolov8_recognition:
  ros__parameters:

    threshold: 0.6
      
    max_sizes:
        - [0.5, 0.5, 0.5]

    model_file: yolov8n.pt

    subscribers:
      
      slop: 0.2
      qos_profile: 10

      image_rgb: /camera/camera/color/image_raw
      camera_info: /camera/camera/color/camera_info
      image_depth: /camera/camera/aligned_depth_to_color/image_raw
      
    publishers:

      object_recognition:
        topic: /fbot_vision/fr/object_recognition
        qos_profile: 10
      
      people_detection:
        topic: /fbot_vision/fr/people_detection
        qos_profile: 10

      debug:
        topic: /fbot_vision/fr/debug
        qos_profile: 10