yolov8_recognition:
  ros__parameters:

    threshold: 0.6

    classes_by_category: '{"Drinks": ["person", "Coke", "Fanta", "Kuat", "Papaya", "Pithula"], 
                          "Cleaning supplies": ["Cloth", "Soap", "SteelWool"], 
                          "Pantry items": ["ToothPick", "Cappuccino", "Gelatin", "MilkCream", "TomatoSauce"], 
                          "Fruits": ["Apple", "Kiwi", "Lemon", "Sicilian_Lemon"], 
                          "Snacks": ["fillet", "Onion", "Pepperoni", "Wafer"]}'
      
    max_sizes:
        - [0.5, 0.5, 0.5]

    model_file: larc_2024_best.pt

    subscribers:
      
      slop: 0.2
      qos_profile: 1

      image_rgb: /cam1/color/image_raw
      camera_info: /cam1/aligned_depth_to_color/camera_info
      image_depth: /cam1/aligned_depth_to_color/image_raw
      
    publishers:

      object_recognition:
        topic: /fbot_vision/fr/object_recognition
        qos_profile: 1
      
      people_detection:
        topic: /fbot_vision/fr/people_detection
        qos_profile: 1

      debug:
        topic: /fbot_vision/fr/debug
        qos_profile: 1